### ISSUE TITLE
Uncaught TypeError: _resolveLibCoreJson2.default.indexOf is not a function

### ISSUE THREAD

**Issue by collinkueter** [fengzilong/atom-select-npm-install#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [atom-select-npm-install](https://github.com/fengzilong/atom-select-npm-install) package 1.0.0

### Stack Trace

Uncaught TypeError: _resolveLibCoreJson2.default.indexOf is not a function

```
At C:\Users\K520749\.atom\packages\atom-select-npm-install\lib\atom-select-npm-install.js:245

TypeError: _resolveLibCoreJson2.default.indexOf is not a function
    at /packages/atom-select-npm-install/lib/atom-select-npm-install.js:245:30
    at Array.filter (native)
    at /packages/atom-select-npm-install/lib/atom-select-npm-install.js:245:7
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.selectionRangeChanged (/app.asar/src/text-editor.js:2608:27)
    at Selection.module.exports.Selection.markerDidChange (/app.asar/src/selection.js:924:26)
    at /app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/app.asar/node_modules/text-buffer/lib/display-marker.js:248:27)
    at /app.asar/node_modules/text-buffer/lib/display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Marker.module.exports.Marker.emitChangeEvent (/app.asar/node_modules/text-buffer/lib/marker.js:417:20)
    at Marker.module.exports.Marker.update (/app.asar/node_modules/text-buffer/lib/marker.js:358:12)
    at Marker.module.exports.Marker.setHeadPosition (/app.asar/node_modules/text-buffer/lib/marker.js:145:19)
    at DisplayMarker.module.exports.DisplayMarker.setHeadBufferPosition (/app.asar/node_modules/text-buffer/lib/display-marker.js:146:32)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (/app.asar/node_modules/text-buffer/lib/display-marker.js:154:19)
    at /app.asar/src/cursor.js:67:31
    at Cursor.module.exports.Cursor.changePosition (/app.asar/src/cursor.js:668:7)
    at Cursor.module.exports.Cursor.setScreenPosition (/app.asar/src/cursor.js:65:19)
    at /app.asar/src/text-editor.js:1856:23
    at TextEditor.module.exports.TextEditor.moveCursors (/app.asar/src/text-editor.js:2078:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/app.asar/src/text-editor.js:1855:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/app.asar/src/text-editor-component.js:721:25)
    at /app.asar/src/text-editor-component.js:3:59)
```

### Commands

```
     -9:59 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -9:58.6.0 core:save (input.hidden-input)
     -9:41.3.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -9:41 editor:delete-line (input.hidden-input)
     -9:39.5.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -9:39.3.0 core:save (input.hidden-input)
     -1:50.3.0 core:backspace (input.hidden-input)
     -1:43 autocomplete-plus:confirm (input.hidden-input)
     -1:41.5.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -1:41.4.0 core:save (input.hidden-input)
     -1:15.8.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:58.8.0 core:backspace (input.hidden-input)
     -0:55.4.0 core:confirm (input.hidden-input)
     -0:02.2.0 atom-select-npm-install:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-select-npm-install 1.0.0 
atom-terminal-panel 4.4.4 
npm-install 4.0.3 
react 0.16.2 
```

**Comment by nanokind** [comment]
Thanks for detailed bug reporting!
Fixed in version 1.0.1, please try updating your package : )
